site_name: MASArena
site_url: https://lins-lab.github.io/masarena
repo_name: LINs-lab/MASArena
repo_url: https://github.com/LINs-lab/MASArena
theme:
  name: material
  icon:
    logo: material/stadium-variant
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Getting started:
    - Installation: quick_start/Installation.md
    - Benchmarking: quick_start/Benchmarking.md
    - Visualization: quick_start/visualization.md
  - System Architecture: system_overview.md
  - Extending: extending.md
  - Tool Integration: tools/tool_integration.md